# Generated by Django 3.2.7 on 2021-09-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('l', 'Lower'), ('ts', 'T shirt'), ('t', 'Track Suit')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
